// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-o26IR-MBD3OLFhbn8Abw_-PmViWUoFg',
    appId: '1:369159641956:web:8700763afcca18beef7871',
    messagingSenderId: '369159641956',
    projectId: 'union-shop-edb12',
    authDomain: 'union-shop-edb12.firebaseapp.com',
    storageBucket: 'union-shop-edb12.firebasestorage.app',
    measurementId: 'G-2X6V5Y5C3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ6Z_e9g_eM45I7XA8G8tTFIqWuLpfmno',
    appId: '1:369159641956:android:7f863d6bf663038cef7871',
    messagingSenderId: '369159641956',
    projectId: 'union-shop-edb12',
    storageBucket: 'union-shop-edb12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsh_YdqkVtQ-834qIe4VFjpFRnElrAeDs',
    appId: '1:369159641956:ios:3af622b7b3971029ef7871',
    messagingSenderId: '369159641956',
    projectId: 'union-shop-edb12',
    storageBucket: 'union-shop-edb12.firebasestorage.app',
    iosBundleId: 'com.example.unionShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsh_YdqkVtQ-834qIe4VFjpFRnElrAeDs',
    appId: '1:369159641956:ios:3af622b7b3971029ef7871',
    messagingSenderId: '369159641956',
    projectId: 'union-shop-edb12',
    storageBucket: 'union-shop-edb12.firebasestorage.app',
    iosBundleId: 'com.example.unionShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-o26IR-MBD3OLFhbn8Abw_-PmViWUoFg',
    appId: '1:369159641956:web:c2c361226fc86f17ef7871',
    messagingSenderId: '369159641956',
    projectId: 'union-shop-edb12',
    authDomain: 'union-shop-edb12.firebaseapp.com',
    storageBucket: 'union-shop-edb12.firebasestorage.app',
    measurementId: 'G-G0KN819SSP',
  );
}
